CREATE TABLE ember (
	id INT(6) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	nev VARCHAR(30) NOT NULL,
	lakhely VARCHAR(50) NOT NULL,
	szuletes DATE NOT NULL
);

CREATE TABLE auto (
	id INT(6) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    marka VARCHAR(30) NOT NULL,
    tipus VARCHAR(30) NOT NULL,
    ar INT NOT NULL,
    ev DATE NOT NULL,
    muszaki BOOLEAN NOT NULL,
    ember_id INT NOT NULL,
    FOREIGN KEY (ember_id) REFERENCES ember(id)
);

CREATE TABLE szerviz(
	id INT(6) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    auto_id INT NOT NULL,
    FOREIGN KEY (auto_id) REFERENCES auto(id),
    datum DATE NOT NULL
);